version: 0.2

phases:
  pre_build:
    commands:
      - echo "Before running tests"
      - pip3 install -r requirements.txt
      
  build:
    commands:
      - echo "Creating dummy data into database"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - '/root/.cache/pip/**/*'