version: 0.2

phases:
    install:
      runtime-versions:
        docker: 18
    pre_build:
      commands:      
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION  --no-include-email)
      - echo Pulling Docker Images for cache ... | tee -a log.txt
      - docker-compose pull --ignore-pull-failures --parallel 2>&1 | tee -a log.txt
    build:
      commands:
      - echo Building the Docker image ... | tee -a log.txt
      - docker-compose build 2>&1 | tee -a log.txt
    post_build:
      commands:
      - echo Pushing the Docker image ... | tee -a log.txt
      - docker-compose push 2>&1 | tee -a log.txt
      - echo printenv | tee -a log.txt
      - printenv | tee -a log.txt
      - echo Sending build log ... | tee -a log.txt
      - aws sns publish --topic-arn "${SNS_TOPIC_ARN}" --subject "AWS CodeBuild Log - ${CODEBUILD_BUILD_ID}" --message file://log.txt
      - echo "CODEBUILD_BUILD_SUCCEEDING:${CODEBUILD_BUILD_SUCCEEDING}" | tee -a sns-message.txt
      - echo Sending notification ...
      - aws sns publish --topic-arn "${SNS_TOPIC_ARN}" --subject "AWS CodeBuild Completed - ${CODEBUILD_BUILD_ID}" --message file://sns-message.txt
