version: '3'

services:
  web:
    build: .
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      wait_hosts: db:5434
    networks:
      - backend
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
  
  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    environment:
      wait_hosts: db:5434
    ports:
      - "8081:80"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
      
