# Generated by Django 3.0.2 on 2020-02-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baserooter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
