# Generated by Django 3.0.2 on 2020-02-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baserooter', '0003_auto_20200224_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='request_id',
            field=models.PositiveIntegerField(default=8908459),
        ),
    ]
