# Generated by Django 3.0.2 on 2020-02-24 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baserooter', '0005_auto_20200224_1156'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmodel',
            name='chat_logs_id_a88483_idx',
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment', to='baserooter.deploymentRequest'),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='normal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal', to='baserooter.requestNormal'),
        ),
        migrations.AddIndex(
            model_name='chatmodel',
            index=models.Index(fields=['id', 'normal', 'deployment', 'message', 'created_at'], name='chat_logs_id_ee3f55_idx'),
        ),
    ]
