# Generated by Django 3.0.2 on 2020-02-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baserooter', '0006_auto_20200224_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentrequest',
            name='requested_branch',
            field=models.CharField(max_length=2000),
        ),
    ]
